### ISSUE TITLE
Dealing with unicode

### ISSUE THREAD

**Issue by angeloklin** [chrisjsewell/ipypublish#45]
Hello Chris,

  I had to make some more change. I know you said I could make a pull request, but I will just add it here.

```
./ipypublish/main.py 

8 import codecs

127    #with open(outpath, "w") as fh:
128    with codecs.open(outpath, "w", encoding='utf-8') as fh:
```

  The original problem was related to:

```
INFO:main:outputting converted file to: ./code/converted/Untitled.tex
Traceback (most recent call last):
  File "/Users/angeloklin/anaconda2/bin/nbpublish", line 138, in <module>
    nbpublish(filepath, **options)   
  File "/Users/angeloklin/anaconda2/bin/nbpublish", line 64, in nbpublish
    create_pdf=create_pdf, pdf_in_temp=pdf_in_temp, pdf_debug=pdf_debug) 
  File "/Users/angeloklin/anaconda2/lib/python2.7/site-packages/ipypublish/main.py", line 127, in publish
    fh.write(body)
UnicodeEncodeError: 'ascii' codec can't encode character u'\xc9' in position 19437: ordinal not in range(128)
```

  Here is some code you can test:
```
import regex
import numpy as np
import pandas as pd

%matplotlib inline
import matplotlib as mpl
mpl.rcParams['axes.formatter.limits'] = (-11, 11)
mpl.rcParams['axes.grid'] = True
mpl.rcParams['figure.autolayout'] = True
mpl.rcParams['figure.figsize'] = (15, 5)
mpl.rcParams['hist.bins'] = 80

import matplotlib.pyplot as plt
plt.ioff()

from IPython.display import display
from IPython.display import Markdown
from IPython.display import Image
```

```
df = pd.DataFrame({'A': [u'CAFÉ-01', u'CAFÉ-02'], 'X': [1, 2]})
```

```
title_1 = 'main_title'
title_2 = regex.sub('_', r'\_', title_1)
display(Markdown('# ' + title_1))
latex = df.to_latex(index=False)
html = df.to_html(index=False)
meta = {'ipub':{'table':{'caption':title_2,'label':'table:tlabel%d' % 1,'placement':'H'}}}
display({'text/latex': latex, 'text/html': html}, raw=True, metadata=meta)
```

```
ind = np.arange(2)
counts = df.X
values = df.A

img = 'test.png'
plt.figure()
plt.bar(ind, counts, zorder=3)
plt.title(title_1)
plt.xticks(ind, values, horizontalalignment='right', rotation=45, zorder=0)
plt.savefig(img)
meta = {'ipub':{'figure':{'caption':title_2,'label':'figure:flabel%d' % 1,'placement':'H'}}}
display(Image(img), metadata=meta)
plt.close()
```

**Comment by chrisjsewell** [comment]
Thanks Angelo, I'm guessing you are using python 2.7, as I don't think this is an issue in Python 3?

**Comment by angeloklin** [comment]
Hello,
  Yes, I am using Python 2.7.13

**Comment by chrisjsewell** [comment]
sorted 395c51b801eb2f2dd78d3a17a1714af81f190869
